import type { Metadata } from "next";
import { Anuphan } from "next/font/google";
import "./globals.css";
import Footer from "@/components/ui/footer";
import { Header } from "@/components/Header";

const anuphan = Anuphan({
  variable: "--font-anuphan-sans",

  subsets: ["latin", "thai"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${anuphan.className}  antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
